name: rust_stm32f446re_blinky

on:
  push:
    branches:
      - '**'
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  thumbv7em-none-eabihf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: thumbv7em-none-eabihf
        override: true
    - name: Prologue
      run: cargo update
    - name: rust_stm32f446re_blinky release
      run: |
        cargo build --release --verbose
    - name: rust_stm32f446re_blinky debug
      run: |
        cargo build --verbose
